config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :customers do
    get 'search', on: :collection
    resources :orders, only: %i[new create]
  end
  resources :orders, only: %i[index show edit update] do
    patch 'finish_cancel', on: :member
    get 'cancel', on: :member
    patch 'finish_cancel', on: :member
    patch 'approve', on: :member
  end
  resources :users, only: %w[index edit update]
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :document, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :phone, presence: true, uniqueness: true
  validates :birth_date, presence: true
  has_many :orders, dependent: :restrict_with_exception
  belongs_to :user

  def identification
    "#{name} - #{document}"
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_customer, only: %i[show edit update destroy]
  before_action :customer_belongs_to_another, only: %i[search]

  def index
    @customers = Customer.all
  end

  def search
    (redirect_to new_customer_path) && return if @customers.empty? && params[:q]
    if customer_belongs_to_another
      flash[:alert] = 'Este cliente pertence a outro vendedor'
    end
    render :index
  end

  def show; end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    @customer.user = current_user
    if @customer.save
      redirect_to @customer, notice: t('.success')
    else
      render :new
    end
  end

  def edit; end

  def update
    if @customer.update(customer_params)
      redirect_to @customer, notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @customer.destroy
    redirect_to customers_path
  end

  private

  def customer_belongs_to_another
    @customers = Customer.where('document LIKE ?', "%#{params[:q]}%")
    @customers.count == 1 && @customers.first.user != current_user \
    && !current_user.admin?
  end

  def customer_params
    params.require(:customer).permit(:name, :address, :document, :email,
                                     :phone, :birth_date)
  end

  def find_customer
    @customer = Customer.find(params[:id])
  end
end

app/views/customers/_form.html.erb
<%= form_with model: @customer, class: 'ls-form ls-form-horizontal row', local: true do |f| %>
  <div class = 'ls-label col-md-12'>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'João da Silva' %>
  </div>
  <div class='ls-label col-md-12'>
    <%= f.label :address %>
    <%= f.text_field :address, placeholder: 'Av. Brasil, 148' %>
  </div>
  <div class='ls-label col-md-6'>
    <%= f.label :document %>
    <%= f.text_field :document, placeholder: '123.456.789-10' %>
  </div>
  <div class='ls-label col-md-6'>
    <%= f.label :email %>
    <%= f.text_field :email, placeholder: 'joao@email.com' %>
  </div>
  <div class='ls-label col-md-6'>  
    <%= f.label :phone %>
    <%= f.text_field :phone, placeholder: '(11)9999-9999' %>
  </div>
  <div class='ls-label col-md-6'>  
    <%= f.label :birth_date %>
    <%= f.date_field :birth_date %>
  </div>
  <div>
    <div class='ls-actions-btn' >
        <%= f.submit 'Salvar', class: 'ls-btn' %>
        <%= link_to 'Cancelar', url_for(:back), class:"ls-btn-danger" %>
    </div>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1 class="ls-title-intro ls-ico-users">Editar <%= Customer.model_name.human(count: 1) %></h1>

<% if @customer.errors.any? %>
  <% @customer.errors.full_messages.each do |message| %>
    <div class="alert alert-danger" role="alert">
      <%= message %>
    </div>
  <% end %>
<% end %>

<%= render partial: 'form', locals: { customer: @customer } %>

app/views/customers/index.html.erb
<h1 class="ls-title-intro ls-ico-users"><%= Customer.model_name.human(count: 2) %></h1>

<%= link_to 'Registrar Novo', new_customer_path, class: 'ls-btn-primary' %>

<div class="ls-box-filter">
  <%= form_tag search_customers_path, method: 'get', class: "ls-form ls-form-inline ls-float-right" do %>
    <%= label_tag :q, 'Pesquisar', class: "ls-label-text ls-hidden-accessible" %>
    <%= text_field_tag :q, nil, placeholder: "CPF do cliente" %>
    <%= submit_tag 'Buscar', class: "ls-btn ls-btn-sm" %>
  <% end %>
</div>

<% if @customers.empty? && params[:q] %>
  <p>Cliente não cadastrado</p>
<% end %>


<table class="ls-table">
    <thead>
      <tr>
        <th><%= Customer.human_attribute_name(:name) %></th>
        <th><%= Customer.human_attribute_name(:email) %></th>
        <th><%= Customer.human_attribute_name(:actions) %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @customers.each do |customer| %>
      <tr id="customer-<%= customer.id %>">
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td>
          <%= link_to customer_path(customer), method: :get do %>
            <i class="ls-ico-zoomin"></i><span class="sr-only">Visualizar</span>
          <% end %>
          <%= link_to edit_customer_path(customer) do %>
            <i class="ls-ico-pencil"></i><span class="sr-only">Editar</span>
          <% end %>
          <%= link_to customer_path(customer), method: :delete, 
          data: { confirm: "Tem certeza de que deseja deletar #{customer.name}?"} do %>
            <i class="ls-ico-remove"></i><span class="sr-only">Deletar</span>
          <% end %>
        </td>
        <td><%= link_to 'Novo Pedido', new_customer_order_path(customer), class: 'ls-btn-sm' %></td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/customers/new.html.erb
<h1 class="ls-title-intro ls-ico-users">Novo <%= Customer.model_name.human(count: 1) %></h1>

<% if @customer.errors.any? %>
  <% @customer.errors.full_messages.each do |message| %>
    <div class="alert alert-danger" role="alert">
      <%= message %>
    </div>
  <% end %>
<% end %>

<%= render partial: 'form', locals: { customer: @customer } %>

app/views/customers/show.html.erb
<h2 class="ls-title-intro ls-ico-users"><%= Customer.model_name.human(count: 1) %></h2>

<table class="ls-table">
  <thead>
    <tr>
      <th><%= Customer.human_attribute_name(:name) %></th>
      <th><%= Customer.human_attribute_name(:address) %></th>
      <th><%= Customer.human_attribute_name(:document) %></th>
      <th><%= Customer.human_attribute_name(:email) %></th>
      <th><%= Customer.human_attribute_name(:phone) %></th>
      <th><%= Customer.human_attribute_name(:birth_date) %></th>
      <th><%= Order.human_attribute_name(:user_id) %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @customer.name %></td>
      <td><%= @customer.address %></td>
      <td><%= @customer.document %></td>
      <td><%= @customer.email %></td>
      <td><%= @customer.phone %></td>
      <td><%= @customer.birth_date %></td>
      <td><%= @customer.user.email %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Editar', edit_customer_path(@customer), class: "ls-btn blue-theme" %>
<%= link_to 'Apagar', customer_path(@customer), method: :delete, class: "ls-btn red-delete",
data: { confirm: "Tem certeza de que deseja deletar #{@customer.name}?"} %>
<%= link_to 'Voltar', customers_path, class:"ls-btn" %>