config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :customers do
    get 'search', on: :collection
    resources :orders, only: %i[new create]
  end
  resources :orders, only: %i[index show edit update] do
    patch 'finish_cancel', on: :member
    get 'cancel', on: :member
    patch 'finish_cancel', on: :member
    patch 'approve', on: :member
  end
  resources :users, only: %w[index edit update]
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :customer
  validates :product_id, :price_id, :plan_id, presence: true
  validates :cancellation_reason, presence: true, if: :cancelled?

  enum status: { open: 0, approved: 4, cancelled: 8 }
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_costumer_order_product, only: %i[create]
  before_action :find_customer, only: %i[new create]
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @product = Product.find(@order.product_id)
    @plan = Plan.find(@order.plan_id)
    @price = Price.find(plan_id: @order.plan_id, price_id: @order.price_id)
  end

  def new
    @order = Order.new
    load_customers_and_products
  end

  def create
    @order.code = SecureRandom.hex(6)
    @order.user = current_user
    @price = Price.find(plan_id: @order.plan_id, price_id: @order.price_id)
    @order.final_price = select_price
    return redirect_to @order, notice: t('.success') if @order.save

    load_customers_and_products
    render :new
  end

  def edit
    @order = Order.find(params[:id])
    load_customers_and_products
  end

  def update
    @order = Order.find(params[:id])
    @order.coupon_name = order_params[:coupon_name]
    @price = Price.find(plan_id: @order.plan_id, price_id: @order.price_id)
    @order.final_price = select_price
    @order.update(order_params)
    redirect_to @order
  end

  def cancel
    @order = Order.find(params[:id])
  end

  def finish_cancel
    @order = Order.find(params[:id])
    @order.status = :cancelled
    return render :cancel unless @order.update(order_params)

    redirect_to order_path(@order), notice: t('.success')
  end

  def approve
    @order = Order.find(params[:id])
    Coupon.burn(@order.coupon_name) if @order.coupon_name.present?
    @order.approved!
    redirect_to @order, notice: t('.success')
  end

  private

  def order_params
    params.require(:order).permit(:product_id, :plan_id,
                                  :price_id, :cancellation_reason,
                                  :coupon_name)
  end

  def load_customers_and_products
    @customers = Customer.all
    @products = Product.all
    @plans = Plan.all
    @prices = Price.all(@plans)
  end

  def set_costumer_order_product
    @customer = Customer.find(params[:customer_id])
    @order = @customer.orders.new(order_params)
    @product = Product.find(@order.product_id)
  end

  def select_price
    return @price.plan_price if order_params[:coupon_name].blank?

    result = @price.discount(@order.coupon_name, @order.product_id)
    return @price.plan_price if result.is_a?(String)

    result
  end

  def find_customer
    @customer = Customer.find(params[:customer_id])
  end
end

app/views/orders/_form.html.erb
<%= form_with model: [@customer, @order], local: true, class: 'ls-form ls-form-horizontal row' do |form| %>
  
  <div class='ls-label col-md-6'>
    <%= form.label :product_id, class: 'ls-label-text' %>
    <div class="ls-custom-select">
      <%= form.collection_select :product_id, @products, :id, :name, prompt: true, class: "ls-custom" %>
    </div>
  </div>

  <div class='ls-label col-md-6'>
    <%= form.label :plan_id, class: 'ls-label-text' %>
      <div class='ls-custom-select'>
        <%= form.collection_select :plan_id, @plans, :id, :name, prompt: true, class: 'ls-custom' %>%
      </div>
  </div>

  <div class='ls-label col-md-6'>
    <%= form.label :price_id, class: 'ls-label-text' %>
    <div class='ls-custom-select'>
      <%= form.collection_select :price_id, @prices, :id, :expose, prompt: true, class: 'ls-custom' %>
    </div>
  </div>

  <div class='ls-label col-md-6'>
    <%= form.label :coupon_name, 'Cupom' %>
    <%= form.text_field :coupon_name %>
  </div>
  
  <p><%= form.submit 'Efetivar', class: 'ls-btn blue-theme' %></p>
<% end %>

app/views/orders/cancel.html.erb
<h1 class="ls-title-intro ls-ico-text">Cancelamento</h1>

<div class="order">
  <%= "Pedido: #{@order.code}" %>
</div>

<% if @order.errors.any? %>
  <div class="errors">
    <% @order.errors.full_messages.each do |message| %>
      <div class="ls-alert-danger"><%= message %></div>
    <% end %>
  </div>
<% end %>

<%= form_with url: {action: :finish_cancel}, model: @order, local: true do |f| %>
  <div class="ls-form ls-form-horizontal row">
    <div class="ls-label col-md-12 form-row">
      <%= f.label :cancellation_reason %>
      <%= f.text_field :cancellation_reason %>
    </div>
  </div>
    <div class="button">
      <%= f.submit 'Enviar', class: "ls-btn-primary"  %>
    </div>
<% end %>

<hr>

app/views/orders/edit.html.erb
<h1 class="ls-title-intro ls-ico-text">Editar <%= Order.model_name.human(count: 1) %></h1>

<%= render partial: 'form', locals: { order: @order } %>

app/views/orders/index.html.erb
<h1 class="ls-title-intro ls-ico-text"><%= Order.model_name.human(count: 2) %></h1>

<table class="ls-table">
    <thead>
      <tr>
        <th><%= Order.human_attribute_name(:code) %></th>
        <th><%= Order.human_attribute_name(:user_id) %></th>
        <th><%= Order.human_attribute_name(:customer) %></th>
        <th><%= Order.human_attribute_name(:product) %></th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr id="order-<%= order.id %>">
        <td><%= order.code %></td>
        <td><%= order.user.email %></td>
        <td><%= order.customer.identification %></td>
        <td><%= order.product_id %></td>
        <td>
          <%= link_to order_path(order), method: :get do %>
            <i class="ls-ico-zoomin"></i><span class="sr-only">Visualizar</span>
          <% end %>
          <%= link_to edit_order_path(order) do %>
            <i class="ls-ico-pencil"></i><span class="sr-only">Editar</span>
          <% end %>
        </td>
      </tr>
    </tbody>
    <% end %>
</table>

app/views/orders/new.html.erb
<h1 class='ls-title-intro ls-ico-text'>Cadastrar <%= Order.model_name.human(count: 1) %></h1>

  <% if @order.errors.any? %>
  <% @order.errors.full_messages.each do |message| %>
    <div class='ls-alert-danger' role='alert'>
      <%= message %>
    </div>
    <% end %>
  <% end %>

<%= render partial: 'form', locals: { order: @order } %>

app/views/orders/show.html.erb
<div class="ls-title-intro ls-ico-text">Pedido: <%= @order.code %></div>
<span class="ls-tag"><div class="status">Status: <%= Order.human_attribute_name(@order.status) %></div></span>
<%= "Preço Total: R$ #{@order.final_price}" %>
<table class="ls-table">
  <thead>
    <tr>
      <th><%= Order.human_attribute_name(:code) %></th>
      <th><%= Order.human_attribute_name(:user_id) %></th>
      <th><%= Order.human_attribute_name(:customer) %></th>
      <th><%= Order.human_attribute_name(:product) %></th>
      <th><%= Order.human_attribute_name(:plan) %></th>
      <th><%= Order.human_attribute_name(:price) %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @order.code %></td>
      <td><%= @order.user.id %></td>
      <td><%= @order.customer.identification %></td>
      <td><%= @product.name %></td>
      <td><%= @plan.name %></td>
      <td><%= @price.expose %></td>
    </tr>
  </tbody>
</table>

<% if current_user.admin? || @order.user == current_user %>
  <% if @order.cancelled? %>
    <div class="reason">
      <h3><%= Order.human_attribute_name(:cancellation_reason)%></h3>
      <div class="why"><%= @order.cancellation_reason %></div>
    </div>
  <% end %>
    <div class="button">
      <% if @order.open? %>
        <%= link_to 'Editar', edit_order_path(@order), class: "ls-btn blue-theme" %>
        <%= link_to 'Cancelar', cancel_order_path(@order), class: "ls-btn red-delete"  %>
        <% if current_user.admin? %>
          <%= link_to 'Aprovar', approve_order_path(@order), method: :patch, class: "ls-btn-primary ls-ico-checkmark"  %>
        <% end %>
      <% end %>
    </div>
<% end %>