config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :customers do
    get 'search', on: :collection
    resources :orders, only: %i[new create]
  end
  resources :orders, only: %i[index show edit update] do
    patch 'finish_cancel', on: :member
    get 'cancel', on: :member
    patch 'finish_cancel', on: :member
    patch 'approve', on: :member
  end
  resources :users, only: %w[index edit update]
end

app/views/layouts/_header.html.erb
<div class="ls-topbar ">
      <!-- Barra de Notificações -->
    <div class="ls-notification-topbar">

        <!-- Dropdown com detalhes da conta de usuário -->
      <div data-ls-module="dropdown" class="ls-dropdown ls-user-account" id="dropdw">
        <a class="ls-ico-user">
          <span class="ls-name"><%= current_user.nickname %></span>
        </a>
        <nav class="ls-dropdown-nav ls-user-menu">
          <ul>
            <li>
              <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </nav>
      </div>
    </div>

    <span class="ls-show-sidebar ls-ico-menu"></span>

    <a href= "/"  class="ls-go-next"><span class="ls-text">Voltar à lista de serviços</span></a>
  


  <!-- Nome do produto/marca com sidebar -->
    <h1 class="ls-brand-name">
      <a href="/" class="ls-ico-cart">
        Vendas
      </a>
    </h1>
</div>

<aside class="ls-sidebar">

  <div class="ls-sidebar-inner">
      <a href="/locawebstyle/documentacao/exemplos//pre-painel"  class="ls-go-prev"><span class="ls-text">Voltar à lista de serviços</span></a>

      <nav class="ls-menu">
        <ul>
          <li>
            <%= link_to 'Clientes', customers_path, class: "ls-ico-user" %>
            <%= link_to 'Pedidos', orders_path, class: "ls-ico-text" %>
            <%= link_to 'Usuários', users_path, class: "ls-ico-user" %>
          </li>
        </ul>
      </nav>


  </div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="ls-theme-light-blue">
  <head>
    <title>QSD - Vendas</title>
    <link rel="icon" href="https://media-exp1.licdn.com/dms/image/C4D0BAQE-jWXQDCr04w/company-logo_200_200/0?e=1590019200&v=beta&t=A1hkzIM2OmQqKvVY3ur1Lrao01nEpPHCAuw57qN2uOM" type="image/x-icon"> 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" type="text/css" href="//assets.locaweb.com.br/locastyle/3.10.1/stylesheets/locastyle.css">
    <link rel="icon" sizes="192x192" href="/locawebstyle/assets/images/ico-boilerplate.png">
    <link rel="apple-touch-icon" href="/locawebstyle/assets/images/ico-boilerplate.png">
  </head>

  <body>

    <% if user_signed_in? %> 
      <%= render '/layouts/header' %>

      <main class="ls-main">
        <div class="container-fluid"> 
          <% if notice %>
            <div class="ls-alert-success alerts" role="alert"> <%= notice %> </div>
          <% end %>
          <% if alert %>
            <div class="ls-alert-warning alerts" role="alert"> <%= alert %> </div>
          <% end %>
          <%= yield %>
        </div>
      </main>
    <% else %>
        <%= yield %>
    <% end %>

    <!-- We recommended use jQuery 1.10 or up -->
    <script type="text/javascript" src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="http://assets.locaweb.com.br/locastyle/3.10.1/javascripts/locastyle.js" type="text/javascript"></script>
  </body>
</html>